import { config } from '@/lib/server/platform';
import type { Catalog } from '@/lib/shared/types';
import type { Metadata } from 'next';
export const origin = () => config('APP_URL') || 'https://foto-digital.stable-elf-2113.chatgpt.site';
export const titles: Record<string, string> = { loja: 'Loja de fotografias e personalizados', revelacao: 'Revelação de fotos em Campo Mourão', polaroid: 'Fotos Polaroid em Campo Mourão', 'foto-3x4': 'Fotos 3x4 em Campo Mourão', documentos: 'Impressão de documentos', personalizados: 'Presentes e produtos personalizados', fotografia: 'Ensaios fotográficos em Campo Mourão', restauracao: 'Restauração de fotos antigas em Campo Mourão', favoritos: 'Meus favoritos', carrinho: 'Meu carrinho', checkout: 'Finalizar pedido', pedido: 'Acompanhar pedido', 'minha-conta': 'Minha conta', sobre: 'Nossa história desde 2003', contato: 'Contato e localização', 'politica-de-privacidade': 'Política de Privacidade', 'politica-de-envio': 'Política de Envio', 'trocas-e-devolucoes': 'Trocas e Devoluções', termos: 'Termos de Uso', admin: 'Administração' };
export const privatePaths = ['admin', 'minha-conta', 'pedido', 'carrinho', 'checkout', 'favoritos'];
export const localBusiness = { '@context': 'https://schema.org', '@type': ['LocalBusiness', 'Organization'], name: 'FOTO DIGITAL', legalName: 'Matsumi & Matsumi Ltda.', taxID: '05.998.428/0001-99', foundingDate: '2003', description: 'Revelação fotográfica, impressões, presentes personalizados e fotografia em Campo Mourão – PR.', telephone: '+554435230433', address: { '@type': 'PostalAddress', streetAddress: 'Rua Brasil, 1367', addressLocality: 'Campo Mourão', addressRegion: 'PR', postalCode: '87302-230', addressCountry: 'BR' } };
export function pageMetadata(path: string[], catalog: Catalog): Metadata { const p = catalog.products.find(p => path[0] === 'produto' && p.slug === path[1]); const s = catalog.services.find(s => path[0] === 'fotografia' && s.slug === path[1]); const category = catalog.categories.find(c => path[0] === 'categoria' && c.slug === path[1]); const title = p?.name ?? s?.name ?? category?.name ?? titles[path[0]] ?? 'FOTO DIGITAL'; const description = p?.description ?? s?.description ?? category?.description ?? 'Suas lembranças merecem sair da tela. Conheça a FOTO DIGITAL em Campo Mourão – PR. Revelação, impressão e personalizados desde 2003.'; const url = origin() + '/' + path.join('/'); return { title, description, alternates: { canonical: url }, openGraph: { title: title + ' | FOTO DIGITAL', description, url, locale: 'pt_BR', type: 'website', ...(p?.image ? { images: [p.image] } : {}) }, robots: privatePaths.includes(path[0]) ? { index: false, follow: false } : { index: true, follow: true } }; }
export function structuredData(path: string[], catalog: Catalog) { if (privatePaths.includes(path[0]))
    return null; const product = catalog.products.find(p => path[0] === 'produto' && p.slug === path[1]); const service = catalog.services.find(s => path[0] === 'fotografia' && s.slug === path[1]); return { '@context': 'https://schema.org', '@graph': [{ '@type': 'BreadcrumbList', itemListElement: [{ '@type': 'ListItem', position: 1, name: 'Início', item: origin() }, { '@type': 'ListItem', position: 2, name: titles[path[0]] ?? path[0], item: origin() + '/' + path[0] }, ...(path[1] ? [{ '@type': 'ListItem', position: 3, name: product?.name ?? service?.name ?? path[1], item: origin() + '/' + path.join('/') }] : [])] }, ...(product ? [{ '@type': 'Product', name: product.name, description: product.description, sku: product.id, ...(product.image ? { image: product.images } : {}), brand: { '@type': 'Brand', name: 'FOTO DIGITAL' }, ...(product.price === null ? {} : { offers: { '@type': 'Offer', priceCurrency: 'BRL', price: ((product.salePrice ?? product.price) / 100).toFixed(2), availability: product.stock === 0 ? 'https://schema.org/OutOfStock' : 'https://schema.org/InStock', url: origin() + '/produto/' + product.slug } }) }] : []), ...(service?.faq.length ? [{ '@type': 'FAQPage', mainEntity: service.faq.map(f => ({ '@type': 'Question', name: f.question, acceptedAnswer: { '@type': 'Answer', text: f.answer } })) }] : [])] }; }
