// Contract test of compiled Worker, D1 and R2. No browser or public requests.
import {Miniflare} from 'miniflare';
import {readFileSync,readdirSync} from 'node:fs';
import {resolve} from 'node:path';
import assert from 'node:assert/strict';
const mf=new Miniflare({modules:true,scriptPath:resolve('dist/server/index.js'),modulesRules:[{type:'ESModule',include:['**/*.js','**/*.mjs'],fallthrough:true}],compatibilityDate:'2026-05-15',compatibilityFlags:['nodejs_compat'],d1Databases:['DB'],r2Buckets:['BUCKET'],assets:{directory:resolve('dist/client'),binding:'ASSETS'},bindings:{APP_URL:'https://fotodigital.test',PIX_KEY:'05998428000199'}});
try{const db=await mf.getD1Database('DB');for(const file of readdirSync('drizzle').filter(f=>f.endsWith('.sql')).sort()){const sql=readFileSync('drizzle/'+file,'utf8').split('--> statement-breakpoint').map(s=>s.trim()).filter(Boolean);await db.batch(sql.map(s=>db.prepare(s)));}
for(const path of ['/','/loja','/revelacao','/sitemap.xml','/robots.txt']){const r=await mf.dispatchFetch('https://fotodigital.test'+path);assert.equal(r.status,200,path+' returned '+r.status);const html=await r.text();assert.ok(html.length>20);if(path==='/')assert.ok(html.includes('lembranças'));console.log(path+' OK');}
const r=await mf.dispatchFetch('https://fotodigital.test/api/session');assert.equal(r.status,200);const cookie=r.headers.get('set-cookie').split(';')[0];const original=Uint8Array.from(Buffer.from('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+a2l0AAAAASUVORK5CYII=','base64'));const init=await mf.dispatchFetch('https://fotodigital.test/api/uploads',{method:'POST',headers:{origin:'https://fotodigital.test',cookie,'content-type':'application/json'},body:JSON.stringify({name:'original.png',mime:'image/png',bytes:original.length,width:1,height:1,consent:true})});assert.equal(init.status,200,await init.clone().text());const {id}=await init.json();const upload=await mf.dispatchFetch('https://fotodigital.test/api/uploads/'+id,{method:'PUT',headers:{origin:'https://fotodigital.test',cookie,'content-length':String(original.length)},body:original});assert.equal(upload.status,200,await upload.clone().text());const download=await mf.dispatchFetch('https://fotodigital.test/api/files/'+id,{headers:{cookie}});assert.deepEqual(new Uint8Array(await download.arrayBuffer()),original);console.log('Worker + D1 + R2: original preservado.');}finally{await mf.dispose();}
