'use client';
import { ArrowRight, ArrowUpRight, Camera, Gift, ImageIcon, MapPin, Printer, ShieldCheck, Star, Truck, Upload } from 'lucide-react';
import Link from 'next/link';
import { useStore } from './context';
import { PhotoImage } from './media';
import { ProductCard } from './ui';
const hero = 'https://images.pexels.com/photos/7015070/pexels-photo-7015070.jpeg?auto=compress&cs=tinysrgb&w=1400';
export function Home() {
    const { catalog } = useStore();
    return <>
 <section className="hero container"><div className="hero-copy"><div className="eyebrow"><span /> SUAS MEMÓRIAS MERECEM MAIS</div><h1>As melhores<br />lembranças merecem<br />sair da <em>tela.</em></h1><p>Fotografias para guardar. Presentes para emocionar.<br className="desktop-break"/> Eternize o que importa, com quem cuida de cada detalhe.</p><div className="hero-buttons"><Link className="btn" href="/revelacao"><Upload size={18}/> Revelar minhas fotos <ArrowRight size={18}/></Link><Link className="text-link" href="/loja">Conhecer produtos <ArrowUpRight size={18}/></Link></div><div className="hero-reassurance"><ShieldCheck size={16}/><span>Seus arquivos originais, preservados com cuidado.</span></div></div><div className="hero-photo"><PhotoImage src={hero} alt="Mãos organizando fotografias impressas sobre uma mesa clara" width={1000} height={1100} fetchPriority="high"/><span className="photo-caption">PARA SENTIR. GUARDAR. REVIVER.</span><div className="hero-note"><span className="note-icon"><ImageIcon size={24} strokeWidth={1.3}/></span><div><strong>Um instante. Para sempre.</strong><span>O digital passa. A memória fica.</span></div></div><div className="photo-index">01 — MEMÓRIAS QUE FICAM</div></div></section>
 <section className="trust-bar container" aria-label="Por que escolher a Foto Digital"><div><Camera /><span><strong>Desde 2003</strong>Cuidado que vem de história</span></div><div><span className="fuji-small">FUJI<br />FILM</span><span><strong>Qualidade Fujifilm</strong>Cor e definição em cada foto</span></div><div><MapPin /><span><strong>Feito em Campo Mourão</strong>Produção local, de perto</span></div><div><Truck /><span><strong>Retire ou receba em casa</strong>Você escolhe como levar</span></div><div><ShieldCheck /><span><strong>Compra com cuidado</strong>Arquivos e dados protegidos</span></div></section>
 <section className="section container"><div className="section-heading"><div><span className="eyebrow">UM MUNDO DE POSSIBILIDADES</span><h2>O que vamos criar hoje?</h2></div><Link className="text-link" href="/loja">Explorar a loja <ArrowRight size={18}/></Link></div><div className="category-tiles">{[{ href: '/revelacao', name: 'Revelação de fotos', text: 'A vida, fora da tela.', icon: ImageIcon }, { href: '/polaroid', name: 'Fotos Polaroid', text: 'Pequenas grandes histórias.', icon: Camera }, { href: '/personalizados', name: 'Personalizados', text: 'Feito para alguém especial.', icon: Gift }, { href: '/documentos', name: 'Impressões', text: 'Praticidade em cada página.', icon: Printer }, { href: '/fotografia', name: 'Ensaios fotográficos', text: 'Um novo olhar sobre você.', icon: Camera }].map(c => <Link className="category-tile" href={c.href} key={c.href}><c.icon strokeWidth={1.3}/><h3>{c.name}</h3><p>{c.text}</p><ArrowUpRight className="category-arrow" size={17}/></Link>)}</div></section>
 {catalog.banners.length > 0 && <section className="container campaign-banners" aria-label="Novidades da loja">{catalog.banners.map(b => <Link href={b.link} key={b.id} className="campaign-banner">{b.image && <PhotoImage src={b.image} alt="" width={400} height={280} loading="lazy"/>}<div><span className="eyebrow">NA FOTO DIGITAL</span><h2>{b.title}</h2><p>{b.subtitle}</p><span className="text-link">Conheça <ArrowRight size={18}/></span></div></Link>)}</section>}<section className="section container favorites-section"><div className="section-heading"><div><span className="eyebrow">ESCOLHIDOS PARA INSPIRAR</span><h2>Pequenos detalhes. Grandes afetos.</h2></div><Link href="/loja" className="text-link">Ver todos os produtos <ArrowRight size={18}/></Link></div><div className="product-grid">{catalog.products.filter(p => p.featured).slice(0, 4).map(p => <ProductCard key={p.id} product={p}/>)}</div><p className="image-disclosure">Imagens ilustrativas. Cada criação ganha a sua história.</p></section>
 <section className="how-section"><div className="container how-grid"><div><span className="eyebrow">DO CELULAR PARA AS SUAS MÃOS</span><h2>Revelar suas fotos<br />é mais simples<br />do que você imagina.</h2><Link href="/revelacao" className="btn">Começar minha revelação <ArrowRight size={18}/></Link></div><div className="how-steps">{[['01', 'Envie suas melhores fotos', 'Escolha várias imagens do celular ou computador. Seus originais são preservados.'], ['02', 'Deixe do seu jeito', 'Selecione tamanho, acabamento e quantidade. Ajuste o enquadramento com facilidade.'], ['03', 'Pronto para virar lembrança', 'Finalize seu pedido e escolha retirar na loja ou receber no seu endereço.']].map(([n, t, d]) => <div className="how-step" key={n}><span>{n}</span><div><h3>{t}</h3><p>{d}</p></div></div>)}</div></div></section>
 <section className="section container story-teaser"><div className="story-image"><PhotoImage src="https://images.pexels.com/photos/8057030/pexels-photo-8057030.jpeg?auto=compress&cs=tinysrgb&w=1000" alt="Mãos folheando um álbum de fotografias" loading="lazy" width={800} height={650}/><span>DESDE 2003</span></div><div><span className="eyebrow">MUITO MAIS DO QUE IMPRIMIR</span><h2>A sua história<br />faz parte da nossa.</h2><p>Há mais de duas décadas, acompanhamos os momentos de quem vive em Campo Mourão. Os primeiros dias, as grandes conquistas, a família que cresce.</p><p>Para nós, cada foto é uma história que merece atenção. E cada cliente, alguém que queremos ver voltar.</p><Link href="/sobre" className="text-link">Conheça a FOTO DIGITAL <ArrowRight size={18}/></Link><div className="story-signature">Tradicional na confiança. Moderna na experiência.</div></div></section>
 {catalog.testimonials.length > 0 && <section className="section container"><div className="section-heading"><div><span className="eyebrow">HISTÓRIAS COMPARTILHADAS</span><h2>O que nossos clientes dizem</h2></div></div><div className="testimonial-grid">{catalog.testimonials.map(t => <blockquote key={t.id}><div aria-label={t.rating + ' estrelas'}>{Array.from({ length: t.rating }, (_, i) => <Star key={i} size={15} fill="currentColor"/>)}</div><p>“{t.comment}”</p><cite>{t.name}</cite></blockquote>)}</div></section>}
 <section className="local-strip container"><div className="local-strip-icon"><MapPin size={28}/></div><div><h3>Seu próximo momento pode começar aqui.</h3><p>Rua Brasil, 1367 · Campo Mourão – PR</p></div><Link href="/contato" className="btn outline">Visite nossa loja <ArrowUpRight size={18}/></Link></section>
 </>;
}
