'use client';
import { Accordion, AccordionContent, AccordionItem, AccordionTrigger } from '@/components/ui/accordion';
import { routeUrl, whats } from '@/lib/shared/brand';
import type { Photo } from '@/lib/shared/types';
import { ArrowRight, ArrowUpRight, Camera, Check, Heart, MapPin, MessageCircle, Phone, Send } from 'lucide-react';
import Link from 'next/link';
import { useState } from 'react';
import { api, useStore } from './context';
import { PhotoImage } from './media';
import { Button, Check as Consent, Notice, PageIntro } from './ui';
import { UploadZone } from './uploads';
export function InquiryForm({ kind = 'contact', subject = '', upload = false }: {
    kind?: 'contact' | 'restoration' | 'photography' | 'product';
    subject?: string;
    upload?: boolean;
}) { const [data, setData] = useState({ name: '', phone: '', email: '', message: subject }); const [photo, setPhoto] = useState<Photo | null>(null); const [consent, setConsent] = useState(false); const [busy, setBusy] = useState(false); const [error, setError] = useState(''); const [success, setSuccess] = useState(''); if (success)
    return <div className="panel inquiry-success"><Check size={38}/><h2>Mensagem recebida.</h2><p>{success}</p><Button variant="outline" onClick={() => { setSuccess(''); setData({ name: '', phone: '', email: '', message: '' }); }}>Enviar outra mensagem</Button></div>; return <form className="panel inquiry-form" onSubmit={async (e) => { e.preventDefault(); setBusy(true); setError(''); try {
    if (!consent)
        throw Error('Autorize o uso das informações para responder à sua solicitação.');
    if (upload && !photo)
        throw Error('Envie a fotografia para avaliação.');
    const r = await api<{
        message: string;
    }>('inquiries', 'POST', { ...data, email: data.email || undefined, kind, photoId: photo?.id, consent });
    setSuccess(r.message);
}
catch (e) {
    setError((e as Error).message);
}
finally {
    setBusy(false);
} }}><h2>{kind === 'restoration' ? 'Conte a história da sua foto.' : 'Vamos conversar?'}</h2>{upload && <><UploadZone multiple={false} onUploaded={setPhoto}/>{photo && <p className="green"><Check size={15}/> {photo.name}</p>}</>}<div className="form-grid"><label>Seu nome<input required autoComplete="name" value={data.name} onChange={e => setData({ ...data, name: e.target.value })}/></label><label>WhatsApp<input required type="tel" autoComplete="tel" value={data.phone} onChange={e => setData({ ...data, phone: e.target.value })}/></label><label className="span-two">E-mail (opcional)<input type="email" autoComplete="email" value={data.email} onChange={e => setData({ ...data, email: e.target.value })}/></label><label className="span-two">{upload ? 'Descreva os danos e o que deseja recuperar' : 'Sua mensagem'}<textarea required minLength={10} maxLength={6000} rows={5} value={data.message} onChange={e => setData({ ...data, message: e.target.value })} placeholder="Conte um pouco do que você precisa."/></label></div><Consent id={'inquiry-consent-' + kind} checked={consent} onChange={setConsent}>Autorizo o uso dos meus dados para atendimento, conforme a <Link href="/politica-de-privacidade">Política de Privacidade</Link>.</Consent>{error && <Notice error>{error}</Notice>}<Button type="submit" busy={busy}><Send size={17}/> {upload ? 'Solicitar orçamento' : 'Enviar mensagem'}</Button></form>; }
export function About() { return <><section className="container about-hero"><div><span className="eyebrow">FOTO DIGITAL · DESDE 2003</span><h1>O tempo passa.<br />O que importa,<br /><em>a gente guarda.</em></h1><p>Algumas histórias cabem em uma fotografia. Outras precisam de um álbum inteiro. Há mais de duas décadas, ajudamos você a guardar todas elas.</p></div><PhotoImage src="https://images.pexels.com/photos/8057030/pexels-photo-8057030.jpeg?auto=compress&cs=tinysrgb&w=1200" alt="Uma pessoa revisitando memórias em um álbum de fotografias" width={800} height={900}/></section><section className="container section about-copy"><span className="eyebrow">RAÍZES EM CAMPO MOURÃO</span><h2>Uma loja feita de histórias.<br />Inclusive a sua.</h2><p>A FOTO DIGITAL nasceu em 2003, em Campo Mourão, com um compromisso que continua guiando nosso trabalho: tratar cada imagem com o cuidado que ela merece.</p><p>Desde então, acompanhamos famílias, profissionais e empresas em seus momentos importantes. Revelamos fotografias, criamos presentes personalizados, imprimimos ideias e registramos novas memórias.</p><p>Na Rua Brasil, 1367, o atendimento continua próximo. Gostamos de ouvir, orientar e encontrar uma solução que faça sentido para cada pessoa. A experiência evoluiu; esse jeito de cuidar continua o mesmo.</p><div className="values-grid">{[[Heart, 'Atendimento de perto', 'Atenção para entender a sua ideia.'], [Camera, 'Qualidade de impressão', 'Qualidade Fujifilm e cuidado nos detalhes.'], [MapPin, 'Produção local', 'Sua encomenda preparada em Campo Mourão.']].map(([Icon, title, text]) => { const C = Icon as typeof Heart; return <div key={title as string}><C strokeWidth={1.2}/><h3>{title as string}</h3><p>{text as string}</p></div>; })}</div><Link href="/contato" className="btn">Venha nos conhecer <ArrowRight size={17}/></Link></section></>; }
export function Contact() { const [showMap, setShowMap] = useState(false); return <div className="container page-space"><PageIntro eyebrow="Fale com a gente" title="Boas ideias começam com uma conversa." description="Estamos em Campo Mourão, pertinho das suas melhores lembranças."/><div className="two-column contact-layout"><div><h2>FOTO DIGITAL</h2><div className="contact-detail"><MapPin /><div><h3>Venha até a loja</h3><p>Rua Brasil, 1367<br />Campo Mourão – PR · CEP 87302-230</p><a href={routeUrl} target="_blank" rel="noreferrer" className="text-link">Traçar uma rota <ArrowUpRight size={16}/></a></div></div><div className="contact-detail"><MessageCircle /><div><h3>Converse pelo WhatsApp</h3><a href={whats()} target="_blank" rel="noreferrer">(44) 99737-2702</a></div></div><div className="contact-detail"><Phone /><div><h3>Ligue para nós</h3><a href="tel:+554435230433">(44) 3523-0433</a></div></div><div className="map-panel">{showMap ? <iframe title="Localização da FOTO DIGITAL em Campo Mourão" src={'https://maps.google.com/maps?q=' + encodeURIComponent('Rua Brasil 1367 Campo Mourão PR') + '&output=embed'} loading="lazy" referrerPolicy="no-referrer-when-downgrade"/> : <div><MapPin size={36}/><strong>Rua Brasil, 1367</strong><p>Carregue o mapa para visualizar a localização no Google Maps.</p><Button variant="outline" onClick={() => setShowMap(true)}>Mostrar mapa</Button></div>}</div></div><InquiryForm /></div></div>; }
export function Restoration() { return <div className="container page-space"><PageIntro eyebrow="Restauração de fotografias" title="Uma nova chance para antigas lembranças." description="O tempo deixa marcas. Nós ajudamos a recuperar a história que existe por trás delas."/><div className="two-column"><div className="restoration-copy"><PhotoImage className="restoration-image" src="https://images.pexels.com/photos/8057030/pexels-photo-8057030.jpeg?auto=compress&cs=tinysrgb&w=1000" alt="Fotografias guardadas em um álbum de família" width={800} height={650}/><h2>Cuidado para resgatar o que importa.</h2><p>A restauração digital pode recuperar fotografias antigas com manchas, rasgos, desbotamento e outros danos. Avaliamos cada imagem para indicar as possibilidades de recuperação e melhoria de nitidez.</p><div className="restoration-list">{['Correção de manchas e danos', 'Recuperação de áreas rasgadas', 'Ajuste de cores e desbotamento', 'Melhoria de nitidez', 'Restauração digital com cuidado'].map(t => <span key={t}><Check size={17}/>{t}</span>)}</div><Notice>O valor depende da complexidade. Envie uma imagem nítida da fotografia para receber um orçamento. O resultado possível será explicado na avaliação.</Notice><a href={whats('Olá! Gostaria de solicitar um orçamento para restauração de uma fotografia.')} target="_blank" rel="noreferrer" className="text-link"><MessageCircle size={17}/> Prefere conversar pelo WhatsApp?</a></div><InquiryForm kind="restoration" upload/></div></div>; }
export function Photography({ slug }: {
    slug?: string;
}) { const { catalog } = useStore(); const selected = slug ?? ''; const service = catalog.services.find(s => s.slug === selected); return <div className="container page-space"><PageIntro eyebrow="Serviços fotográficos" title={service?.name ?? 'Seu momento. Nosso olhar.'} description={service?.description ?? 'Ensaios e registros feitos com direção, sensibilidade e atenção a quem você é.'}/>{service ? <><Link href="/fotografia" className="text-link">Todos os ensaios</Link><div className="service-detail"><div className="service-gallery">{service.gallery.map((img, i) => <PhotoImage key={img + i} src={img} alt={'Inspiração para ' + service.name.toLowerCase()} width={800} height={1000} loading="lazy"/>)}<p className="image-disclosure">Imagens de inspiração. O portfólio da FOTO DIGITAL pode ser consultado com nossa equipe.</p></div><div className="panel"><span className="eyebrow">FEITO PARA VOCÊ</span><h2>Vamos planejar seu ensaio?</h2><p>Conte sua ideia, consulte as datas e receba uma proposta adequada ao seu momento.</p><a className="btn full" href={whats('Olá! Gostaria de solicitar orçamento e disponibilidade para ' + service.name + '.')} target="_blank" rel="noreferrer"><MessageCircle size={17}/> Consultar pelo WhatsApp</a><Accordion type="single" collapsible>{service.faq.map((f, i) => <AccordionItem value={String(i)} key={f.question}><AccordionTrigger>{f.question}</AccordionTrigger><AccordionContent>{f.answer}</AccordionContent></AccordionItem>)}</Accordion></div></div><InquiryForm kind="photography" subject={'Gostaria de saber mais sobre ' + service.name + '. '}/></> : <><div className="service-grid">{catalog.services.map(s => <Link href={'/fotografia/' + s.slug} className="service-card" key={s.id}><PhotoImage src={s.image} alt={'Inspiração para ' + s.name.toLowerCase()} width={800} height={1000} loading="lazy"/><div><span>FOTO DIGITAL · CAMPO MOURÃO</span><h2>{s.name}</h2><p>{s.description}</p><span className="service-arrow"><ArrowUpRight size={22}/></span></div></Link>)}</div><p className="image-disclosure">Imagens ilustrativas de inspiração. Consulte o portfólio da loja.</p><div className="local-strip"><div><h3>Não sabe por onde começar?</h3><p>Conte sua ideia. A gente ajuda a planejar.</p></div><a className="btn" href={whats('Olá! Quero conversar sobre um ensaio fotográfico.')} target="_blank" rel="noreferrer">Falar sobre meu ensaio <ArrowRight size={17}/></a></div></>}</div>; }
const policies: Record<string, {
    title: string;
    sections: [
        string,
        string
    ][];
}> = {
    'politica-de-privacidade': { title: 'Política de Privacidade', sections: [['Quem cuida dos seus dados', 'A FOTO DIGITAL, nome fantasia de Matsumi & Matsumi Ltda., CNPJ 05.998.428/0001-99, é responsável pelos dados utilizados no atendimento e nos pedidos realizados neste site. Nosso endereço é Rua Brasil, 1367, Campo Mourão – PR, CEP 87302-230.'], ['Dados que utilizamos', 'Coletamos os dados que você informa, como nome, e-mail, telefone, CPF/CNPJ, endereço, arquivos, personalizações e histórico de pedidos. Usamos essas informações para atender solicitações, produzir e entregar encomendas, processar pagamentos e cumprir obrigações aplicáveis.'], ['Suas fotografias', 'Os arquivos enviados são privados e acessíveis à conta responsável e à equipe autorizada. Os originais são preservados separadamente das miniaturas e das instruções de impressão. Não utilizamos suas fotos em publicidade ou portfólio sem uma autorização específica. Envie apenas imagens que você tem autorização para usar.'], ['Compartilhamento necessário', 'Dados de pagamento são tratados pela operadora contratada. Informações de entrega são fornecidas à transportadora quando houver envio. Serviços de hospedagem e armazenamento processam os dados necessários ao funcionamento do site. Dados de cartão não são armazenados pela FOTO DIGITAL.'], ['Prazo de conservação', 'As fotografias ficam disponíveis pelo prazo informado no envio, configurado pela loja. Após esse período, podem ser excluídas de forma segura, considerando a situação dos pedidos. Registros de compra podem ser mantidos para obrigações legais e atendimento.'], ['Cookies e serviços externos', 'Usamos cookies essenciais para a sessão e o carrinho. Favoritos de visitantes podem ser guardados neste dispositivo. Imagens ilustrativas são carregadas de bancos de imagens. O mapa só é carregado ao ser solicitado; ao usá-lo, aplicam-se também as políticas do Google.'], ['Seus direitos e contato', 'Você pode solicitar informações sobre o tratamento, acesso, correção ou exclusão de dados e revogação de consentimento, observadas as hipóteses legais de conservação. Entre em contato pelo WhatsApp (44) 99737-2702 ou telefone (44) 3523-0433. Podemos solicitar informações para confirmar sua identidade antes de atender.']] },
    'politica-de-envio': { title: 'Política de Envio e Retirada', sections: [['Retirada gratuita', 'Você pode retirar seu pedido na FOTO DIGITAL, Rua Brasil, 1367, Campo Mourão – PR, CEP 87302-230. Aguarde a atualização “Pronto para retirada”. A retirada local não tem cobrança de frete.'], ['Envio para o seu endereço', 'As opções disponíveis são apresentadas após a consulta do CEP. O valor e o prazo dependem da transportadora, do destino e das características do pedido. Se a consulta não estiver disponível, fale com nossa equipe. Não são apresentadas cotações estimadas sem confirmação.'], ['Produção e transporte', 'O prazo de produção é informado no produto e começa após a confirmação do pagamento e dos arquivos necessários. O prazo de transporte é contado separadamente, após a postagem. Havendo algum impedimento na produção, entraremos em contato.'], ['Acompanhe seu pedido', 'As atualizações ficam na área Meus Pedidos. Quando houver envio, a loja informa o código de rastreio. Confira o endereço antes da confirmação; caso precise corrigir algum dado, fale conosco o quanto antes.']] },
    'trocas-e-devolucoes': { title: 'Trocas e Devoluções', sections: [['Conte o que aconteceu', 'Se houver divergência, defeito ou dano no seu pedido, entre em contato pelo WhatsApp (44) 99737-2702. Informe o número do pedido e descreva o problema. Fotos do produto e da embalagem podem ajudar no atendimento.'], ['Compras realizadas pela internet', 'Nas compras fora do estabelecimento, o Código de Defesa do Consumidor prevê o direito de arrependimento no prazo de 7 dias, contado da assinatura ou do recebimento, conforme o caso. Para solicitar atendimento, utilize nossos canais de contato. Os direitos legais do consumidor serão respeitados.'], ['Produtos personalizados', 'Revise nomes, datas, textos, arquivos e enquadramentos antes de confirmar. Caso perceba um erro, avise a loja o mais rápido possível para avaliarmos a etapa de produção e a solução. A personalização não elimina os direitos previstos em lei.'], ['Solução e restituição', 'Cada solicitação será analisada com as informações do pedido. A equipe orientará sobre coleta, devolução, substituição ou restituição, conforme o caso e a legislação aplicável. Não envie produtos sem receber as instruções de atendimento.']] },
    'termos': { title: 'Termos de Uso', sections: [['Sobre a loja', 'Este site pertence a Matsumi & Matsumi Ltda., CNPJ 05.998.428/0001-99, nome fantasia FOTO DIGITAL, com endereço na Rua Brasil, 1367, Campo Mourão – PR. Ao realizar um pedido, informe dados corretos e confira produtos, quantidades e personalizações.'], ['Produtos, preços e disponibilidade', 'Valores válidos são apresentados em reais no momento da compra. Produtos sem preço cadastrado são exibidos sob consulta. Descontos, cupons, disponibilidade e total são verificados antes da criação do pedido. A expressão Qualidade Fujifilm refere-se à impressão utilizada pela empresa e não representa declaração de representação oficial.'], ['Arquivos e personalizações', 'Você declara ter autorização para utilizar os arquivos enviados. Preserve uma cópia dos seus originais. As prévias e os avisos de resolução auxiliam a escolha, mas iluminação, foco, proporção e diferenças entre telas e impressão influenciam o resultado. A loja entrará em contato se identificar algum impedimento.'], ['Pagamento e confirmação', 'O pedido só segue para produção após a confirmação do pagamento e a conferência das informações necessárias. No PIX, o recebimento deve ser confirmado. Nas operações por cartão, a cobrança ocorre no ambiente da operadora. Parcelamento e juros dependem das condições apresentadas pela operadora, sem taxas presumidas.'], ['Conta e uso responsável', 'Mantenha suas credenciais protegidas. Não utilize o serviço para enviar arquivos ilegais, maliciosos ou que violem direitos de terceiros. As fotografias são destinadas à produção e ao atendimento do pedido, com acesso restrito.'], ['Atendimento', 'Dúvidas, correções e solicitações podem ser encaminhadas pelo WhatsApp (44) 99737-2702 ou telefone (44) 3523-0433. Consulte também as políticas de Privacidade, Envio e Trocas e Devoluções.']] }
};
export function PolicyPage({ slug }: {
    slug: string;
}) { const { catalog } = useStore(); const policy = policies[slug]; return <article className="container policy-page"><PageIntro title={policy.title} description="Informações claras para comprar com tranquilidade."/><p className="muted small">Atualizado em 8 de setembro de 2026.</p>{policy.sections.map(([title, text]) => <section key={title}><h2>{title}</h2><p>{text}</p>{title === 'Prazo de conservação' && <p>Prazo atualmente configurado para as fotografias: <strong>{catalog.settings.retentionDays} dias</strong> a partir do envio.</p>}</section>)}{slug === 'trocas-e-devolucoes' && <a href="https://www.planalto.gov.br/ccivil_03/leis/l8078compilado.htm" target="_blank" rel="noreferrer" className="text-link">Consultar o Código de Defesa do Consumidor <ArrowUpRight size={16}/></a>}<a className="btn outline" href={whats('Olá! Tenho uma dúvida sobre ' + policy.title.toLowerCase() + '.')} target="_blank" rel="noreferrer">Falar com a FOTO DIGITAL <MessageCircle size={17}/></a></article>; }
