'use client';
import { Sheet, SheetContent, SheetDescription, SheetTitle, SheetTrigger } from '@/components/ui/sheet';
import { brand, routeUrl, whats } from '@/lib/shared/brand';
import { ArrowUpRight, Camera, ChevronDown, Heart, MapPin, Menu, MessageCircle, Phone, Search, ShoppingBag, UserRound, X } from 'lucide-react';
import Link from 'next/link';
import { useEffect, useRef, useState } from 'react';
import { useStore } from './context';
import { PhotoImage } from './media';
export function Logo() { return <Link href="/" className="logo" aria-label="Foto Digital, início"><Camera size={35} strokeWidth={1.4}/><div><strong>FOTO<span>DIGITAL</span></strong><small>DESDE 2003 · CAMPO MOURÃO</small></div></Link>; }
const nav = [['/loja', 'Todos os produtos'], ['/revelacao', 'Revelação de fotos'], ['/polaroid', 'Polaroid'], ['/personalizados', 'Personalizados'], ['/documentos', 'Impressões'], ['/fotografia', 'Fotografia'], ['/sobre', 'Nossa história']];
export function Header({ path }: {
    path: string;
}) {
    const { cart, catalog } = useStore();
    const [search, setSearch] = useState('');
    const [open, setOpen] = useState(false);
    const [menu, setMenu] = useState(false);
    const searchRef = useRef<HTMLDivElement>(null);
    const results = search.trim().length > 1 ? catalog.products.filter(p => (p.name + ' ' + p.description + ' ' + p.category + ' ' + p.tags.join(' ')).toLocaleLowerCase().includes(search.toLocaleLowerCase())).slice(0, 5) : [];
    useEffect(() => { const close = (e: MouseEvent) => { if (!searchRef.current?.contains(e.target as Node))
        setOpen(false); }; document.addEventListener('click', close); return () => document.removeEventListener('click', close); }, []);
    return <><div className="announcement"><span>Boas lembranças começam aqui.</span><strong>5% de desconto no PIX</strong><span className="announcement-end">Desde 2003 eternizando momentos</span></div><header className="site-header"><div className="header-main container"><div className="mobile-menu"><Sheet open={menu} onOpenChange={setMenu}><SheetTrigger asChild><button className="icon-button" aria-label="Abrir menu"><Menu /></button></SheetTrigger><SheetContent side="left" className="menu-sheet"><SheetTitle>FOTO DIGITAL</SheetTitle><SheetDescription>Encontre a sua próxima lembrança.</SheetDescription><nav>{nav.map(([href, label]) => <Link href={href} key={href} onClick={() => setMenu(false)}>{label}</Link>)}</nav><Link href="/contato" onClick={() => setMenu(false)}>Fale com a gente</Link></SheetContent></Sheet></div><Logo /><div className="global-search" ref={searchRef}><form action="/loja"><Search size={19}/><input name="q" aria-label="Buscar produtos" placeholder="O que você quer eternizar hoje?" value={search} onChange={e => { setSearch(e.target.value); setOpen(true); }} onFocus={() => setOpen(true)} onKeyDown={e => { if (e.key === 'Escape')
        setOpen(false); }}/>{search && <button type="button" aria-label="Limpar busca" onClick={() => setSearch('')}><X size={16}/></button>}</form>{open && search.length > 1 && <div className="search-results">{results.length ? results.map(p => <Link key={p.id} href={'/produto/' + p.slug} onClick={() => setOpen(false)}>{p.image ? <PhotoImage src={p.image} alt="" width={44} height={44}/> : <Camera />}<div><strong>{p.name}</strong><small>{p.category}</small></div><ArrowUpRight size={16}/></Link>) : <p>Nenhum produto encontrado.</p>}<Link href={'/loja?q=' + encodeURIComponent(search)} onClick={() => setOpen(false)}>Ver todos os resultados <ArrowUpRight size={16}/></Link></div>}</div><div className="header-actions"><Link href="/favoritos" className="icon-button desktop-icon" aria-label="Meus favoritos"><Heart size={23}/></Link><Link href="/minha-conta" className="account-link" aria-label="Minha conta"><UserRound size={23}/><span>Olá, bem-vindo(a)<strong>Minha conta</strong></span></Link><Link href="/carrinho" className="bag-link icon-button" aria-label={'Carrinho com ' + cart.count + ' itens'}><ShoppingBag size={24}/><span>{cart.count}</span></Link></div></div><div className="nav-border"><nav className="main-nav container" aria-label="Navegação principal">{nav.map(([href, label], i) => <Link key={href} href={href} className={path === href ? 'active' : ''}>{i === 0 && <Menu size={17}/>} {label}{i === 0 && <ChevronDown size={13}/>}</Link>)}<Link className="contact-nav" href="/contato">Fale com a gente <ArrowUpRight size={15}/></Link></nav></div></header></>;
}
export function Footer() { return <footer><div className="footer-main container"><div className="footer-brand"><Logo /><p>Desde 2003, transformando momentos<br />em lembranças que ficam.</p><a href={routeUrl} target="_blank" rel="noreferrer"><MapPin size={17}/><span>Rua Brasil, 1367 · Centro<br />Campo Mourão – PR · 87302-230</span></a></div><div><h3>Explore a loja</h3>{[['/revelacao', 'Revelação de fotos'], ['/personalizados', 'Personalizados'], ['/fotografia', 'Serviços fotográficos'], ['/sobre', 'Nossa história'], ['/contato', 'Contato']].map(([h, l]) => <Link href={h} key={h}>{l}</Link>)}</div><div><h3>Estamos por aqui</h3><Link href="/minha-conta">Minha conta</Link><Link href="/minha-conta/pedidos">Meus pedidos</Link><Link href="/favoritos">Meus favoritos</Link><a href={whats()} target="_blank" rel="noreferrer"><MessageCircle size={16}/> {brand.whatsapp}</a><a href="tel:+554435230433"><Phone size={16}/> {brand.phone}</a></div><div className="footer-quality"><h3>Detalhes que fazem a diferença</h3><strong className="fuji">QUALIDADE FUJIFILM</strong><p>Cuidado em cada impressão.</p><div className="payment-marks"><span>PIX</span><span>CRÉDITO</span><span>DÉBITO*</span></div><small>*Conforme disponibilidade da operadora.</small></div></div><div className="footer-bottom container"><span>© {new Date().getFullYear()} FOTO DIGITAL · Matsumi & Matsumi Ltda.<br />CNPJ 05.998.428/0001-99</span><div>{[['/politica-de-privacidade', 'Privacidade'], ['/politica-de-envio', 'Envio'], ['/trocas-e-devolucoes', 'Trocas e devoluções'], ['/termos', 'Termos de uso']].map(([h, l]) => <Link href={h} key={h}>{l}</Link>)}</div></div></footer>; }
export function WhatsApp({ path }: {
    path: string;
}) { const msg = path.startsWith('/restauracao') ? 'Olá! Gostaria de solicitar um orçamento para restauração de uma fotografia.' : path.startsWith('/produto') ? 'Olá! Vi este produto no site da FOTO DIGITAL e gostaria de tirar uma dúvida: ' + path : undefined; return <a className="whatsapp-float" href={whats(msg)} aria-label="Conversar com a FOTO DIGITAL no WhatsApp" target="_blank" rel="noreferrer"><MessageCircle size={24}/><span>Como podemos ajudar?</span></a>; }
